name: Build EXE

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-binutils

      - name: Build (same as your local)
        shell: msys2 {0}
        run: |
          /ucrt64/bin/windres app.rc -O coff -o app.o
          g++ unlocker.cpp app.o -o Genshin_FPS_Unlock.exe -lcomdlg32 -lshell32

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Genshin-FPS-Unlock-exe
          path: Genshin_FPS_Unlock.exe